version: "1.0"
stages:
  - "clone"
  - "build"
  - "integration"

#services:
#  name: mongo
#  composition:
#    mongo:
#      image: mongo:latest
#      ports:
#        - 27017

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    stage: "clone"

  build_image:
    title: "Building App image"
    type: "build"
    image_name: "ahromis/demochat"
    working_directory: "${{clone}}"
    tag: "${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"

  integration_step:
    title: "Running integration tests"
    stage: "integration"
    image: nhoag/curl:latest
    command: bash -c "sleep 30 && curl http://app:5000/" | echo 'works'
    services:
      composition:
        mongo:
          image: mongo:latest
          ports:
            - 27017
        app:
          image: ${{build_image}}
          working_directory: /root/demochat
          commands:
            - 'npm run start'
