version: "1.0"
stages:
  - "clone"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    stage: "clone"

  deploy:
    title: Storing Helm chart
    type: helm
    stage: deploy
    working_directory: ./demochat
    arguments:
      action: push
      chart_name: charts/demochat
      helm_version: 3.0.3
      kube_context: 'gke_codefresh-309818_us-central1-c_codefresh'

#  deployStaging:
#    title: Deploying to Staging
#    type: helm
#    stage: staging
#    working_directory: ./demochat
#    arguments:
#      action: install
#      chart_name: charts/demochat
#      release_name: demochat-staging
#      helm_version: 3.5.0
#      kube_context: 'gke_codefresh-309818_us-central1-c_codefresh'
#      namespace: staging
#      custom_value_files:
#      - ./helm/values-staging.yaml

#   env:
#      name: Demochat Staging
#      endpoints:
#      - name: app
#        url: https://demochat.qa.deerwald.com
#      type: helm-release
#      change: '${{CF_COMMIT_MESSAGE}}'
#      filters:
#      - cluster: gke_codefresh-309818_us-central1-c_codefresh
#        namespace: demochat-staging

