apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: demochat
spec:
  tls:
  - hosts:
      - "{{ .Values.ingress.host }}"
    secretName: deerwald-qa-tls
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
        - backend:
            serviceName: demochat
            servicePort: 5000
          path: /
